name: Run Telegram Bot

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger this on

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package

      - name: Run bot
        run: java -jar target/your-bot-jar-name.jar
